version: "3.9"

services:
    backend:
        image: "node"
        volumes:
            - "./backend:/var/www/html"
        working_dir: "/var/www/html"
        environment:
            PORT: ${BACKEND_PORT}
            FRONTEND_URL: ${FRONTEND_URL}
            MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin
            CDM_CARD_NO: ${CDM_CARD_NO}

        ports:
            - "3001:3001"
        command: bash -c "npm install && npm run dev"
        depends_on:
            - mongo
        networks:
            - sail
    backend-2:
        image: "node"
        volumes:
            - "./backend-2:/var/www/html"
        working_dir: "/var/www/html"
        environment:
            PORT: 3002
            FRONTEND_URL: ${FRONTEND_URL}
            MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin
            CDM_CARD_NO: ${CDM_CARD_NO}

        ports:
            - "3002:3002"
        command: bash -c "npm install && npm run dev"
        depends_on:
            - mongo
        networks:
            - sail

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        env_file:
            - .env
        networks:
            - sail

volumes:
    mongo-data:

networks:
    sail:
