/**
 * 精密採点DX-Gのデータを変換する
 */
// eslint-disable-next-line
export const convertDataDamDxgFields = (scoreDetail: any) => ({
  scoringDxgId: scoreDetail.scoringDxgId,
  lastTotalPoints: scoreDetail.lastTotalPoints,
  bonusType: scoreDetail.bonusType,
  bonusPoint: scoreDetail.bonusPoint,
  expressionGraphPointsSection: [
    scoreDetail.expressionGraphPointsSection01,
    scoreDetail.expressionGraphPointsSection02,
    scoreDetail.expressionGraphPointsSection03,
    scoreDetail.expressionGraphPointsSection04,
    scoreDetail.expressionGraphPointsSection05,
    scoreDetail.expressionGraphPointsSection06,
    scoreDetail.expressionGraphPointsSection07,
    scoreDetail.expressionGraphPointsSection08,
    scoreDetail.expressionGraphPointsSection09,
    scoreDetail.expressionGraphPointsSection10,
    scoreDetail.expressionGraphPointsSection11,
    scoreDetail.expressionGraphPointsSection12,
    scoreDetail.expressionGraphPointsSection13,
    scoreDetail.expressionGraphPointsSection14,
    scoreDetail.expressionGraphPointsSection15,
    scoreDetail.expressionGraphPointsSection16,
    scoreDetail.expressionGraphPointsSection17,
    scoreDetail.expressionGraphPointsSection18,
    scoreDetail.expressionGraphPointsSection19,
    scoreDetail.expressionGraphPointsSection20,
    scoreDetail.expressionGraphPointsSection21,
    scoreDetail.expressionGraphPointsSection22,
    scoreDetail.expressionGraphPointsSection23,
    scoreDetail.expressionGraphPointsSection24,
  ],
  expressionGraphIndexSection: [
    scoreDetail.expressionGraphIndexSection01,
    scoreDetail.expressionGraphIndexSection02,
    scoreDetail.expressionGraphIndexSection03,
    scoreDetail.expressionGraphIndexSection04,
    scoreDetail.expressionGraphIndexSection05,
    scoreDetail.expressionGraphIndexSection06,
    scoreDetail.expressionGraphIndexSection07,
    scoreDetail.expressionGraphIndexSection08,
    scoreDetail.expressionGraphIndexSection09,
    scoreDetail.expressionGraphIndexSection10,
    scoreDetail.expressionGraphIndexSection11,
    scoreDetail.expressionGraphIndexSection12,
    scoreDetail.expressionGraphIndexSection13,
    scoreDetail.expressionGraphIndexSection14,
    scoreDetail.expressionGraphIndexSection15,
    scoreDetail.expressionGraphIndexSection16,
    scoreDetail.expressionGraphIndexSection17,
    scoreDetail.expressionGraphIndexSection18,
    scoreDetail.expressionGraphIndexSection19,
    scoreDetail.expressionGraphIndexSection20,
    scoreDetail.expressionGraphIndexSection21,
    scoreDetail.expressionGraphIndexSection22,
    scoreDetail.expressionGraphIndexSection23,
    scoreDetail.expressionGraphIndexSection24,
  ],
});
