/**
 * 精密採点Aiのデータを変換する
 */
// eslint-disable-next-line
export const convertDataDamAiFields = (scoreDetail: any) => ({
  scoringAiId: scoreDetail.scoringAiId,
  accentCount: scoreDetail.accentCount,
  aiSensitivityBonus: scoreDetail.aiSensitivityBonus,
  aiSensitivityMeterAdd: scoreDetail.aiSensitivityMeterAdd,
  aiSensitivityMeterDeduct: scoreDetail.aiSensitivityMeterDeduct,
  aiSensitivityPoints: scoreDetail.aiSensitivityPoints,
  edgeVoiceCount: scoreDetail.edgeVoiceCount,
  fadeout: scoreDetail.fadeout,
  maxTotalPoints: scoreDetail.maxTotalPoints,
  spare1: scoreDetail.spare1,
  spare2: scoreDetail.spare2,
  aiSensitivityGraphAddPoints: [
    Number(scoreDetail.aiSensitivityGraphAddPointsSection01),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection02),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection03),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection04),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection05),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection06),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection07),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection08),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection09),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection10),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection11),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection12),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection13),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection14),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection15),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection16),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection17),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection18),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection19),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection20),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection21),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection22),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection23),
    Number(scoreDetail.aiSensitivityGraphAddPointsSection24),
  ],
  aiSensitivityGraphDeductPoints: [
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection01),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection02),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection03),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection04),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection05),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection06),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection07),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection08),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection09),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection10),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection11),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection12),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection13),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection14),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection15),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection16),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection17),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection18),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection19),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection20),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection21),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection22),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection23),
    Number(scoreDetail.aiSensitivityGraphDeductPointsSection24),
  ],
  // ここは文字列だった気がする（B'00, B'01, B'10）
  aiSensitivityGraphIndex: [
    scoreDetail.aiSensitivityGraphIndexSection01,
    scoreDetail.aiSensitivityGraphIndexSection02,
    scoreDetail.aiSensitivityGraphIndexSection03,
    scoreDetail.aiSensitivityGraphIndexSection04,
    scoreDetail.aiSensitivityGraphIndexSection05,
    scoreDetail.aiSensitivityGraphIndexSection06,
    scoreDetail.aiSensitivityGraphIndexSection07,
    scoreDetail.aiSensitivityGraphIndexSection08,
    scoreDetail.aiSensitivityGraphIndexSection09,
    scoreDetail.aiSensitivityGraphIndexSection10,
    scoreDetail.aiSensitivityGraphIndexSection11,
    scoreDetail.aiSensitivityGraphIndexSection12,
    scoreDetail.aiSensitivityGraphIndexSection13,
    scoreDetail.aiSensitivityGraphIndexSection14,
    scoreDetail.aiSensitivityGraphIndexSection15,
    scoreDetail.aiSensitivityGraphIndexSection16,
    scoreDetail.aiSensitivityGraphIndexSection17,
    scoreDetail.aiSensitivityGraphIndexSection18,
    scoreDetail.aiSensitivityGraphIndexSection19,
    scoreDetail.aiSensitivityGraphIndexSection20,
    scoreDetail.aiSensitivityGraphIndexSection21,
    scoreDetail.aiSensitivityGraphIndexSection22,
    scoreDetail.aiSensitivityGraphIndexSection23,
    scoreDetail.aiSensitivityGraphIndexSection24,
  ],
});
